sudo: false
language: rust
rust: nightly
script:
  - cargo build
  - cargo test
env:
  global:
  - secure: xHUGJn89lFSrNutHity1M+97tZjQ5ff0tjNbjDwchujL5BgP9aLVY3O7Wg3LoO/sWN8TYtO5sDVBy/8nV6HvVU28k/1ZLOQzDc2WeXIVBGdqOxB9QtLAkIa4aRHA6yhC65vI9zeTzGnOo166++4HvtU5DN5Bkq+Zm+AZxXVEZM+3AeiqaOLly6AzgUWCQf2TF8/aqU9K2sb6yBYsrBi8m4yMVYoC3pKlVlk6NbevhG059V/46zNQqDwbryLa+MPiRsnMuDVU2xAaKd4OAIxVNOfYmEETHnpZ1UNXMCc85XHOeu2+AVxJJzdb3U3jb7ixZ8z14ZwUBHzVgMv2p2lHvSL7TPQ/y+N4NOg7FEptxVzlzYT9h/5Nrx2sqVkgezzFf3L9vJ7W9CNHTBuW29gKpnNxuiFw0ZOU5c7St/tgccjzphOJaUvT1n7KuZinRktz7lIawShIuC8z1BChC2nDJoe650nvtUEETU++nj+rEdFmJwwGg+bz+vjsfFiXRxC6Fswe3Q7xrVrq+PDO51ZqZbOj1vj6Kxq1CdnHvvjNCb+wF4ihM4qf48Hnor80f+ciLwK5vENF6cMsSsTcEXHgXd1HwDGOkaBwkhQjwqg3fStuARmCQYmTnxuNHSNXnnazZq4MpRn4cqcr/ZeZsXOvJQ4BEA9HLacSD5Ii03D4u7A=
before_deploy:
  - cargo doc
  - .travis/publish.sh
  - cargo package
  - cargo publish --token $CRATES_TOKEN
deploy:
  provider: releases
  api_key:
    secure: PMTzLk29n+dKEqxO7ZR9Jim5ygPyr6jYWjo+YalDx/t89GLn9vpkSR5oGLBws1sMSoiSiY5kd5wua3CwBkg4pc83+AnAWjHaM/rCfbSBQ2Tpsh8A81gWDdu5g8+bqwE12PYAIAX05z7r6BwpFwKm0gvGhlW6vd6QCHS1gE42aXIGJHD/7BJxloO46yPJY9RPtk/6LbtJCIp9tFN7izW5Kqqo/J6BE/DtxVS4ei9s+Gh93WHyz71bV7c09EzYXzYKZPWhF38bHp06pDqopc8KtJ+f73guPbkgCjaMZv91c5P+omJNrwk2iRRyOY8JRiPcH3VuJCReg8OViKdarA0ysQcc0YnoKJF/NU01NUrVn5qmNio/RJ+WHN1+QIZfeLfYnnirfMPyBneSjXb5D9VxGSdy9YdQI5xf0uKpikDjU0aDIxxSD9Vo5AsfckgYP1ev0SyGsrxVGucnaCdDbI+0f7z0IkHMi3NeOE8eY/hoaeuUfslt1WtkX4gFeziN5M5UOja1Zt1dVSUW/Cl29pi9iW5TKytIp7d2uiAgLyFPHuJp0mIy6UZgjNYdjDm8njvSo6vBMbxcY6cuzPDkICNl1n8c9qR2X7gk3Kx8VBT7813wPz71kha3bGi91tTOQuWOgz49qwNN4F0QFV0jyJNjpkvsjm/FmIs/BPXV9iCmh0U=
  file: target/debug/libseax_scheme.rlib
  on:
    repo: hawkw/seax_scheme
    tags: true
